require("codrut/core/options")
require("codrut/core/packer")
require("codrut/core/colorscheme")
require("codrut/core/keymaps")

require("codrut/plugins/comment")
require("codrut/plugins/nvim-tree")
require("codrut/plugins/lualine")
require("codrut/plugins/telescope")
require("codrut/plugins/nvim-cmp")
require("codrut/plugins/treesitter")
require("codrut/plugins/autopairs")
require("codrut/plugins/gitsigns")
require("codrut/plugins/colorizer")
require("codrut/plugins/toggleterm")
require("codrut/plugins/alpha")

require("codrut/plugins/lsp/mason")
require("codrut/plugins/lsp/lspsaga")
require("codrut/plugins/lsp/lspconfig")
require("codrut/plugins/lsp/null-ls")
