require("codrut/core/options")
require("codrut/core/packer")
require("codrut/core/colorscheme")
require("codrut/core/keymaps")

require("codrut/plugins/comment")
require("codrut/plugins/nvim-tree")
require("codrut/plugins/lualine")
require("codrut/plugins/telescope")
require("codrut/plugins/nvim-cmp")
